# https-redirect middleware to redirect HTTP to HTTPS
# Usage: <router>.middlewares=https-redirect@file
http:
  middlewares:
    https-redirect:
      redirectScheme:
        scheme: https
        permanent: true