name: Continuous Deployment
on:
  push:
    branches:
      - 'master'
    paths-ignore:
    - 'ansible/**'
    - 'terraform/**'

env:
  DEPLOY_TARGET_URL: blog.20dots.com
  DEPLOY_TARGET_USER: vita

jobs:
  build:
    name: Build & Push Production Docker Image
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ghcr.io/justindoody/app-platform-traefik:${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      -
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  deploy:
    needs: build
    name: Deploy Traefik
    runs-on: ubuntu-latest
    env:
      DOCKER_CONFIG: $HOME/.docker
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: SSH Agent
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
      -
        name: Setup SSH Known Hosts
        run: |
          mkdir -p -m 0700 ~/.ssh

          echo "Add domain to known hosts"
          ssh-keyscan -t rsa -p 22 ${{ env.DEPLOY_TARGET_URL }} > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
      -
        name: Add docker production context
        run: |
          docker context create production \
                 --docker host=ssh://${{ env.DEPLOY_TARGET_USER }}@${{ env.DEPLOY_TARGET_URL }}
      -
        name: Deploy application services to swarm
        run: |
          docker --context production \
                 stack deploy \
                 --prune \
                 --with-registry-auth \
                 --compose-file ./docker/traefik-stack.yml \
                 traefik
